import FooterBar from "./components/footer";
import LandingSection from "./components/landing";
import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "./globals.css";
import Contact from "./components/contact";
import Aboutme from "./components/aboutme";
import Technologies from "./components/technologies";

// const karlaSans = Karla({
//   variable: "--font-karla-sans",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${karlaSans.variable} antialiased`}
      >
        <LandingSection />
        <Aboutme />
        <Technologies />
        {children}
        <Contact />
        <FooterBar />
      </body>
    </html>
  );
}
