import FooterBar from "./footer";
import LandingSection from "./landing";
import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "./globals.css";
import Contact from "./contact";
import Aboutme from "./aboutme";

const karlaSans = Karla({
  variable: "--font-karla-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${karlaSans.variable} antialiased`}
      >
        <LandingSection />
        <Aboutme />
        {children}
        <Contact />
        <FooterBar />
      </body>
    </html>
  );
}
