import FooterBar from "./footer";
import LandingSection from "./landing";
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Karla } from "next/font/google";
import "./globals.css";
import Contact from "./contact";

const karlaSans = Karla({
  variable: "--font-karla-sans",
  subsets: ["latin"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${karlaSans.variable} antialiased`}
      >
        <LandingSection />
        {children}
        <Contact />
        <FooterBar />
      </body>
    </html>
  );
}
